name: Format, Lint & Test
on: [push]
jobs:
  format-lint-test:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Format dynflows
        working-directory: dynflows
        run: |
            uv run black . --check
            uv run isort . --profile black --check
      - name: Format dpe_experiments
        working-directory: dpe_experiments
        run: |
            uv run black . --check
            uv run isort . --profile black --check
      - name: Lint dynflows
        working-directory: dynflows
        run: uv run pylint src --errors-only
      - name: Lint dpe_experiments
        working-directory: dpe_experiments
        run: uv run pylint src --errors-only
      - name: Test dynflows
        working-directory: dynflows
        run:  uv run pytest
